import { describe, expect, test } from "bun:test";
import { runFeatureStage } from "../src/internal/stages";
import type {
  GenerationContext,
  NormalizedGenerationConfig,
} from "../src/types";

const config: NormalizedGenerationConfig = {
  seed: "feature-markup-test",
  width: 100,
  height: 25,
  requestedCells: 4,
  culturesCount: 1,
  statesCount: null,
  townsCount: null,
  jitter: 0,
  heightNoise: 0,
  heightTemplate: "continents",
  seaLevel: 20,
  hiddenControls: {
    sizeVariety: 1,
    growthRate: 1,
    statesGrowthRate: 1,
    provincesRatio: 40,
    religionsNumber: null,
  },
  climate: {
    temperatureEquator: 27,
    temperatureNorthPole: -30,
    temperatureSouthPole: -15,
    elevationExponent: 1.8,
    lakeElevationLimit: 20,
    precipitation: 100,
    mapSize: 100,
    latitude: 50,
    longitude: 50,
    winds: [225, 45, 225, 315, 135, 315],
  },
  layers: {
    physical: true,
    cultures: false,
    settlements: false,
    politics: false,
    religions: false,
    military: false,
    markers: false,
    zones: false,
  },
};

const createContext = (heights: readonly number[]): GenerationContext => {
  const cellCount = heights.length;

  return {
    config,
    random: () => 0.5,
    grid: {
      spacing: 25,
      cellsX: cellCount,
      cellsY: 1,
    },
    internal: {
      cultureTypes: ["Generic"],
      burgPackIds: new Uint32Array(1),
      packRetentionCoast: null,
      packRetentionWaterType: null,
    },
    world: {
      cellCount,
      cellsX: new Float32Array(
        Array.from({ length: cellCount }, (_, index) => 12.5 + index * 25),
      ),
      cellsY: new Float32Array(cellCount),
      cellsBorder: new Uint8Array(cellCount),
      cellsArea: new Float32Array(cellCount),
      cellsH: Uint8Array.from(heights),
      cellsCulture: new Uint16Array(cellCount),
      cultureCount: 0,
      cultureSeedCell: new Uint32Array(1),
      cultureSize: new Uint32Array(1),
      cellsBurg: new Uint16Array(cellCount),
      burgCount: 0,
      burgCell: new Uint32Array(1),
      burgX: new Float32Array(1),
      burgY: new Float32Array(1),
      burgPopulation: new Uint16Array(1),
      burgCapital: new Uint8Array(1),
      burgPort: new Uint8Array(1),
      burgCulture: new Uint16Array(1),
      cellsState: new Uint16Array(cellCount),
      stateCount: 0,
      stateCenterBurg: new Uint16Array(1),
      stateCulture: new Uint16Array(1),
      stateForm: new Uint8Array(1),
      stateCells: new Uint32Array(1),
      routeCount: 0,
      routeFromState: new Uint16Array(1),
      routeToState: new Uint16Array(1),
      routeKind: new Uint8Array(1),
      routeWeight: new Uint16Array(1),
      cellRouteOffsets: new Uint32Array(cellCount + 1),
      cellRouteNeighbors: new Uint32Array(0),
      cellRouteKinds: new Uint8Array(0),
      cellsProvince: new Uint16Array(cellCount),
      provinceCount: 0,
      provinceState: new Uint16Array(1),
      provinceCenterCell: new Uint32Array(1),
      provinceCells: new Uint32Array(1),
      cellsReligion: new Uint16Array(cellCount),
      religionCount: 0,
      religionSeedCell: new Uint32Array(1),
      religionType: new Uint8Array(1),
      religionSize: new Uint32Array(1),
      cellsMilitary: new Uint16Array(cellCount),
      militaryCount: 0,
      militaryCell: new Uint32Array(1),
      militaryState: new Uint16Array(1),
      militaryType: new Uint8Array(1),
      militaryStrength: new Uint16Array(1),
      markerCount: 0,
      markerCell: new Uint32Array(1),
      markerType: new Uint8Array(1),
      markerStrength: new Uint8Array(1),
      cellsZone: new Uint16Array(cellCount),
      zoneCount: 0,
      zoneSeedCell: new Uint32Array(1),
      zoneType: new Uint8Array(1),
      zoneCells: new Uint32Array(1),
      cellsFeature: new Uint8Array(cellCount),
      cellsFeatureId: new Uint32Array(cellCount),
      featureCount: 0,
      featureType: new Uint8Array(1),
      featureGroup: new Uint8Array(1),
      featureLand: new Uint8Array(1),
      featureBorder: new Uint8Array(1),
      featureSize: new Uint32Array(1),
      featureFirstCell: new Uint32Array(1),
      cellsCoast: new Int8Array(cellCount),
      cellsLandmass: new Uint32Array(cellCount),
      landmassCount: 0,
      landmassKind: new Uint8Array(1),
      landmassSize: new Uint32Array(1),
      landmassBorder: new Uint8Array(1),
      cellsTemp: new Int8Array(cellCount),
      cellsPrec: new Uint8Array(cellCount),
      cellsFlow: new Uint32Array(cellCount),
      cellsRiver: new Uint32Array(cellCount),
      cellsBiome: new Uint8Array(cellCount),
      cellsWaterbody: new Uint32Array(cellCount),
      waterbodyCount: 0,
      waterbodyType: new Uint8Array(1),
      waterbodyGroup: new Uint8Array(1),
      waterbodySize: new Uint32Array(1),
      packCellCount: 0,
      gridToPack: new Int32Array(cellCount),
      packToGrid: new Uint32Array(0),
      packX: new Float32Array(0),
      packY: new Float32Array(0),
      packH: new Uint8Array(0),
      packArea: new Float32Array(0),
      packNeighborOffsets: new Uint32Array(1),
      packNeighbors: new Uint32Array(0),
      packCellsFeatureId: new Uint32Array(0),
      packFeatureCount: 0,
      packFeatureType: new Uint8Array(1),
      packFeatureFeatureId: new Uint32Array(1),
      packFeatureBorder: new Uint8Array(1),
      packFeatureSize: new Uint32Array(1),
      packFeatureFirstCell: new Uint32Array(1),
      packFeatureGroup: new Uint8Array(1),
      packFeatureChainOffsets: new Uint32Array(1),
      packFeatureVertexOffsets: new Uint32Array(1),
      packFeatureVertices: new Uint32Array(0),
      packFeatureShorelineOffsets: new Uint32Array(1),
      packFeatureShoreline: new Uint32Array(0),
      packCoast: new Int8Array(0),
      packHaven: new Int32Array(0),
      packHarbor: new Uint8Array(0),
      packVertexX: new Float32Array(0),
      packVertexY: new Float32Array(0),
      packCellVertexOffsets: new Uint32Array(1),
      packCellVertices: new Uint32Array(0),
      vertexX: new Float32Array(0),
      vertexY: new Float32Array(0),
      cellVertexOffsets: new Uint32Array(cellCount + 1),
      cellVertices: new Uint32Array(0),
      cellNeighborOffsets: Uint32Array.from([0, 1, 3, 5, 6]),
      cellNeighbors: Uint32Array.from([1, 0, 2, 1, 3, 2]),
    },
  };
};

describe("grid feature markup", () => {
  test("marks land coast and deep water bands like upstream grid features", () => {
    const context = createContext([35, 28, 19, 5]);

    runFeatureStage(context);

    expect(Array.from(context.world.cellsFeature)).toEqual([1, 1, 0, 0]);
    expect(Array.from(context.world.cellsCoast)).toEqual([2, 1, -1, -2]);
  });
});
